### ISSUE TITLE
Quest: Get Listed on MDC-Web's README

### ISSUE THREAD

**Issue by Kerrick** [secondstreet/ember-material-components-web#66]
I'd love to get listed on the official [Google Material Components (Web) README](https://github.com/material-components/material-components-web) as the first (and only?) Ember.js implementation. For this to work, we have to meet [three criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#examples):

- [ ] Serve components in an à-la-carte delivery model (#65)
- [X] Have existed for longer than 6 weeks and show continued maintenance over time (#18 etc)
- [ ] Provide usage documentation per component (#47)
